/**
 * 模块名称：Layer 2 trip data
 * 职责描述：提供江西六日游第二层日级 POI、住宿基地、行李策略、相邻交通段和预算估算
 * 输入/输出：无输入；输出 tripData 给浏览器全局变量和 Node.js 测试
 * 依赖关系：无外部依赖
 * 注意事项：价格为 12306/公开来源/变量估算；车次、酒店与班车需在出发前刷新
 */

const tripData = {
  layer: 3,
  title: "江西六日游 Layer 3 三清山精细路线",
  subtitle: "2026-05-21 至 2026-05-26｜双人｜体力较好｜带行李箱｜三清山必去｜删除婺源/篁岭",
  arrival: {
    stationId: "nanchang-west-station",
    time: "2026-05-21 13:00",
    note: "到达后先去固定酒店放行李，不拖箱游览。",
  },
  departure: {
    stationId: "shangrao-station",
    time: "2026-05-26 17:00",
    note: "删减一天后按5月26日17:00从上饶站离开规划；若实际票仍为5月27日，可把最后一晚恢复为上饶或三清山脚休整夜。",
  },
  fixedHotelIds: {
    nanchang: "nanchang-hanting-xuefu-east",
    jingdezhenSuggested: "jingdezhen-hanting-taoxichuan",
    sanqingshanSuggested: "sanqingshan-hanting-jinsha",
  },
  budgetRules: {
    travelers: 2,
    taxiCnyPerKm: 3,
    maxNonEssentialTaxiMin: 60,
    taxiPricingNote: "按用户指定变量3元/公里估算；南昌政府公开巡游出租车标准为普通车型6元/2公里、1.9元/公里，高档车型8元/2公里、2.1元/公里。为覆盖网约车、候时、绕行和夜间浮动，本攻略暂用3元/公里作为保守变量。",
    hotelPricingNote: "酒店价为中端连锁双人间规划占位估算，酒店平台价格实时波动，锁单前需刷新。",
  },
  budget: {
    currency: "CNY",
    notes: [
      "交通估算只包含行程内相邻转场，不包含出发地往返江西的大交通。",
      "打车按整车计价；高铁、班车按2人计价。",
      "酒店按1间房计价；如两人分房，住宿总额需要乘以2。",
    ],
    hotelNights: [
      { city: "南昌", base: "汉庭南昌红谷滩学府大道东地铁站店", date: "2026-05-21", nights: 1, unitCny: 260, source: "中端连锁估算，需平台刷新" },
      { city: "南昌", base: "汉庭南昌红谷滩学府大道东地铁站店", date: "2026-05-22", nights: 1, unitCny: 260, source: "中端连锁估算，需平台刷新" },
      { city: "景德镇", base: "陶溪川/陶阳里附近中端酒店", date: "2026-05-23", nights: 1, unitCny: 280, source: "携程/华住页面可查酒店信息，价格需刷新" },
      { city: "景德镇", base: "陶溪川/陶阳里附近中端酒店", date: "2026-05-24", nights: 1, unitCny: 280, source: "携程/华住页面可查酒店信息，价格需刷新" },
      { city: "三清山", base: "金沙索道口附近中端酒店", date: "2026-05-25", nights: 1, unitCny: 300, source: "山脚住宿估算，价格需刷新" },
    ],
    railTickets: [
      { day: 3, train: "D6360", from: "南昌东", to: "景德镇北", unitCny: 86, travelers: 2, source: "12306 MCP 2026-05-09可查样例，目标日需刷新" },
      { day: 5, train: "G1456", from: "景德镇北", to: "上饶", unitCny: 63.5, travelers: 2, source: "12306 MCP 2026-05-09可查样例，目标日需刷新" },
    ],
  },
  luggagePolicy: {
    mode: "drop-store-first",
    rules: [
      "抵达日先到酒店放行李。",
      "5月23南昌退房后不安排拖箱景点，直接去南昌东站。",
      "景德镇两晚建议住陶溪川/陶阳里附近，方便夜间步行。",
      "5月25删除婺源/篁岭，不使用长途连续打车，改为景德镇北高铁到上饶后公共班车/接驳到三清山脚。",
      "5月26不带箱上三清山，行李留酒店；下山后用公共班车/接驳回上饶站。",
    ],
  },
  assumptions: [
    "演唱会场馆未知，5月22晚预留 18:00 后给演唱会和交通。",
    "景德镇与三清山住宿为路线推荐点，实际酒店确定后需要替换坐标并重算相邻段。",
    "已按用户要求删除婺源/篁岭并压缩为6天；如果实际离开仍是5月27，可增加上饶或三清山脚恢复日。",
    "单次非必要打车不超过1小时；长距离跨城优先高铁/班车。",
    "天气预报距离出行日较远，需要出发前 3-5 天刷新。",
    "12306核验：2026-05-23与2026-05-25精确车票当前返回空结果，需临近开售后刷新；下方车次节奏来自12306 MCP可查样例，不作为最终购票承诺。",
  ],
  railChecks: {
    source: "12306 MCP",
    checkedAt: "2026-04-26",
    queryLimitations: "目标日期2026-05-23和2026-05-25查询返回空结果异常，按可查样例2026-05-09和近期班次提取节奏；购票前必须重新查12306。",
    stationCodes: {
      "南昌东": "NUG",
      "南昌西": "NXG",
      "南昌": "NCG",
      "景德镇北": "JDG",
      "上饶": "SRG",
    },
    items: [
      {
        id: "day3-nanchang-east-jingdezhen-north",
        title: "Day 3 南昌东 -> 景德镇北",
        targetDate: "2026-05-23",
        comparableDate: "2026-05-09",
        recommendedTrain: "D6360",
        recommendedMinutes: 54,
        recommendation: "主推按D6360 15:18-16:12节奏购票：退房后可从容到南昌东站，带行李安检和候车缓冲更稳；若想早到可看G3068 13:15-13:57，但12:30从酒店出发会偏紧。",
        candidates: [
          { train: "G3068", depart: "13:15", arrive: "13:57", duration: "00:42", secondSeat: "85元", note: "最快但缓冲偏紧" },
          { train: "D6360", depart: "15:18", arrive: "16:12", duration: "00:54", secondSeat: "86元", note: "主推，节奏稳" },
          { train: "G9874", depart: "15:48", arrive: "16:49", duration: "01:01", secondSeat: "75元", note: "备选" },
          { train: "D2202", depart: "15:59", arrive: "16:59", duration: "01:00", secondSeat: "86元", note: "备选" },
        ],
      },
      {
        id: "day5-jingdezhen-shangrao-transfer",
        title: "Day 5 景德镇北 -> 上饶",
        targetDate: "2026-05-25",
        comparableDate: "2026-05-09",
        recommendedTrain: "G1456",
        recommendedMinutes: 52,
        recommendation: "删除婺源后，主推G1456 09:03-09:55到上饶，再接公共班车/接驳去三清山脚，避免两段长途打车。",
        candidates: [
          { train: "G1456", depart: "09:03", arrive: "09:55", duration: "00:52", secondSeat: "63.5元", note: "主推，早到上饶便于接班车" },
          { train: "G3098", depart: "11:29", arrive: "12:23", duration: "00:54", secondSeat: "63.5元", note: "午前备选" },
          { train: "G5036", depart: "11:46", arrive: "12:39", duration: "00:53", secondSeat: "65.5元", note: "中午备选" },
          { train: "G9874", depart: "16:52", arrive: "17:51", duration: "00:59", secondSeat: "65.5元", note: "太晚，不推荐当天进山脚" },
        ],
      },
    ],
  },
  layer3: [
    {
      id: "sanqingshan-layer3",
      poiId: "sanqingshan-jinsha-lower",
      title: "三清山金沙索道一日压缩精细路线",
      sourceNotes: [
        "高德 POI 校验：金沙索道上站、女神峰、巨蟒出山、阳光海岸、西海岸均有可定位点。",
        "公开/官方信息显示三清山索道和景区时间会按季节、周末、天气和客流调整，出发前必须刷新。",
        "本层按2026-05-26 17:00上饶站离开倒推，优先保守下山和返站时间。",
      ],
      entrance: {
        recommended: "金沙索道",
        reason: "酒店靠近金沙索道，且 Day 6 需要当天回上饶站，东上东下最少换乘、最容易控时。",
        avoid: "外双溪索道会增加跨入口交通和取行李复杂度，除非金沙索道停运或强限流。",
      },
      ticketAndCableway: {
        refreshRequired: true,
        planningWindow: "尽量07:15前到金沙索道下站，抢首批或早批上山；以景区当日公告、预约平台和酒店前台确认为准。",
        planningCost: "门票+上下行索道价格按官方/平台当日为准，本攻略暂不把景区门票计入总预算，避免过期价格误导。",
        lastDownRule: "13:30后不再向更远支线扩展；14:00前开始下山/返酒店取行李。",
      },
      routeOptions: [
        {
          id: "compressed-classic",
          name: "压缩经典线",
          minutes: 330,
          steps: [
            "金沙索道下站 -> 上站",
            "巨蟒出山/女神峰",
            "南清园核心观景",
            "阳光海岸高空栈道",
            "西海岸视野段",
            "按体力回金沙索道下山",
          ],
          useWhen: "天气清楚、索道排队可控、07:45前能到达上站。",
        },
        {
          id: "easy-core",
          name: "轻量核心线",
          minutes: 240,
          steps: [
            "金沙索道上站",
            "巨蟒出山",
            "女神峰",
            "南清园短环线",
            "金沙索道下山",
          ],
          useWhen: "前一晚休息不足、山上雾大、腿部状态一般，或索道排队超过45分钟。",
        },
        {
          id: "bad-weather",
          name: "雨雾备选线",
          minutes: 180,
          steps: [
            "只保留金沙索道上下",
            "巨蟒出山/女神峰附近短停",
            "放弃西海岸和阳光海岸远支线",
            "提前回酒店取行李并改早一班接驳回上饶",
          ],
          useWhen: "雷雨、大雾、栈道湿滑、景区广播限制通行或当天必须稳住17:00离开。",
        },
      ],
      photoCheckpoints: [
        "巨蟒出山：上午光线更稳，先拍标志性峰体。",
        "女神峰/东方女神：和巨蟒出山相邻，适合压缩线首段完成。",
        "阳光海岸：晴天视野好时保留，雾大时可删。",
        "西海岸：高空栈道视野段，只有在时间和体力都富余时进入。",
      ],
      supplies: [
        "轻装上山，行李留酒店或前台；只带水、雨衣、防晒、充电宝和少量补给。",
        "山上餐饮和厕所按景区开放情况变化，进入远支线前先补水上厕所。",
        "5月山上温差和阵雨概率较高，雨衣优先于雨伞。",
      ],
      risks: [
        "索道排队或限流会吞掉核心游览时间，超过45分钟就切轻量核心线。",
        "栈道雨雾湿滑时不要赶西海岸/阳光海岸远支线。",
        "必须盯住下行索道和返上饶接驳末班，13:30后不再继续远离金沙索道。",
        "如公共班车时间不匹配，优先提前下山，不用连续长途打车硬赶。",
      ],
    },
  ],
  mustSeePoiIds: ["sanqingshan-jinsha-lower"],
  pois: [
    { id: "nanchang-west-station", name: "南昌西站", city: "南昌", type: "station", lng: 115.792938, lat: 28.622886, core: true, openTime: "到达 13:00", rating: null, note: "带箱抵达，优先打车/地铁到酒店。" },
    { id: "nanchang-hanting-xuefu-east", name: "汉庭酒店(南昌红谷滩学府大道东地铁站店)", city: "南昌", type: "hotel", lng: 115.839866, lat: 28.658605, core: true, openTime: "固定住宿", rating: 4.7, note: "你的南昌固定酒店，靠近学府大道东地铁站和万象城。" },
    { id: "nanchang-vientiane", name: "南昌万象城/赣江南岸", city: "南昌", type: "rest-food", lng: 115.8385, lat: 28.6558, core: true, openTime: "商场营业时间以当日为准", rating: null, note: "到达日低强度晚餐和补给，步行约480米。" },
    { id: "jiangxi-museum", name: "江西省博物馆", city: "南昌", type: "museum", lng: 115.881823, lat: 28.7059, core: true, openTime: "周二至周日 09:00-17:00，16:00停止入馆", rating: 4.9, note: "南昌最适合作为第一天文化主菜，5月22周五开放。" },
    { id: "tengwang-pavilion", name: "滕王阁旅游区/午餐区", city: "南昌", type: "landmark-food", lng: 115.88111, lat: 28.681387, core: true, openTime: "08:00-22:00，最晚进入21:00", rating: 4.0, note: "省博后直接南下到滕王阁附近午餐，不再回酒店走回头路。" },
    { id: "wanshou-palace", name: "万寿宫历史文化街区", city: "南昌", type: "old-street", lng: 115.887019, lat: 28.674121, core: true, openTime: "街区24小时，店铺多为日间至晚间", rating: 4.8, note: "适合滕王阁后步行串联，吃饭和老城氛围。" },
    { id: "bayi-memorial", name: "南昌八一起义纪念馆", city: "南昌", type: "memorial", lng: 115.889435, lat: 28.67467, core: true, openTime: "常规约09:00-17:00，需以官方当日公告为准", rating: 4.7, note: "与万寿宫很近，可作为可选短停。" },
    { id: "nanchang-east-station", name: "南昌东站", city: "南昌", type: "station", lng: 116.020724, lat: 28.613654, core: true, openTime: "高铁站", rating: null, note: "南昌到景德镇高铁优先从这里走，带箱打车更稳。" },
    { id: "jingdezhen-north-station", name: "景德镇北站", city: "景德镇", type: "station", lng: 117.242517, lat: 29.339669, core: true, openTime: "24小时", rating: null, note: "抵达后先去酒店放行李。" },
    { id: "jingdezhen-hanting-taoxichuan", name: "汉庭酒店(景德镇陶溪川文创街区店)", city: "景德镇", type: "hotel", lng: 117.226494, lat: 29.290014, core: true, openTime: "推荐住宿基地", rating: 4.8, note: "建议住陶溪川/陶阳里一带，夜间步行体验更好。" },
    { id: "taoxichuan", name: "陶溪川文创街区", city: "景德镇", type: "creative-district", lng: 117.226, lat: 29.29, core: true, openTime: "街区开放，店铺以当日为准", rating: null, note: "抵达夜低压力逛吃；也可根据市集日期调整。" },
    { id: "ceramic-museum", name: "景德镇中国陶瓷博物馆", city: "景德镇", type: "museum", lng: 117.17553, lat: 29.29324, core: true, openTime: "周二至周日 09:00-17:00，周一闭馆", rating: 4.8, note: "先建立陶瓷史脉络，再去古窑和御窑会更有层次。" },
    { id: "ancient-kiln", name: "景德镇古窑民俗博览区", city: "景德镇", type: "living-craft", lng: 117.184813, lat: 29.28343, core: true, openTime: "08:00-17:00", rating: 4.6, note: "看制瓷工艺和古窑形态，和博物馆不重复。" },
    { id: "imperial-kiln", name: "景德镇御窑博物馆/陶阳里", city: "景德镇", type: "museum-night", lng: 117.207107, lat: 29.296615, core: true, openTime: "周二至周日 09:00-22:00，周一闭馆", rating: 4.8, note: "建筑与夜景价值高，适合放在晚段。" },
    { id: "shangrao-station", name: "上饶站", city: "上饶", type: "station", lng: 118.006797, lat: 28.490464, core: true, openTime: "高铁/离开枢纽", rating: 4.6, note: "景德镇转三清山的公共交通中转点，旁边汽车东站可接旅游班车。" },
    { id: "sanqingshan-hanting-jinsha", name: "汉庭酒店(上饶三清山金沙索道店)", city: "上饶三清山", type: "hotel", lng: 118.100321, lat: 28.918452, core: true, openTime: "推荐住宿基地", rating: 4.6, note: "靠近金沙索道，便于行李留店和早上山。" },
    { id: "sanqingshan-jinsha-lower", name: "三清山金沙索道下站", city: "上饶三清山", type: "mountain-gate", lng: 118.093508, lat: 28.923283, core: true, openTime: "索道以当日公告为准", rating: 4.3, note: "三清山压缩版一日游入口，早上第一批上山，下午回上饶离开。" },
    { id: "sanqingshan-jinsha-upper", name: "三清山金沙索道上站", city: "上饶三清山", type: "cableway", lng: 118.076082, lat: 28.907096, core: true, openTime: "索道以当日公告为准", rating: 4.3, note: "Amap POI B0FFFQZC5O；上站后开始山上步行环线。" },
    { id: "sanqingshan-goddess", name: "三清山女神峰/东方女神", city: "上饶三清山", type: "photo-spot", lng: 118.071571, lat: 28.905645, core: true, openTime: "旺季常见08:00-17:00/周末07:30-17:30，需当日刷新", rating: 4.0, note: "Amap POI 女神峰；与巨蟒出山组成金沙索道上站后的第一组核心看点。" },
    { id: "sanqingshan-python", name: "三清山巨蟒出山", city: "上饶三清山", type: "photo-spot", lng: 118.069954, lat: 28.905746, core: true, openTime: "07:00-17:30，需当日刷新", rating: 4.2, note: "Amap POI B03190139E；三清山标志性峰体，优先拍。" },
    { id: "sanqingshan-sunshine-coast", name: "三清山阳光海岸", city: "上饶三清山", type: "skywalk", lng: 118.073365, lat: 28.906546, core: true, openTime: "08:00-16:30，需当日刷新", rating: 4.1, note: "晴天视野价值高；雨雾或时间不足时可删。" },
    { id: "sanqingshan-west-coast", name: "三清山西海岸景区", city: "上饶三清山", type: "skywalk", lng: 118.06025, lat: 28.904391, core: true, openTime: "旺季常见08:00-17:00/周末07:30-17:30，需当日刷新", rating: 4.2, note: "高空栈道视野段，只有体力和时间充足才进入。" },
  ],
  days: [
    {
      day: 1,
      date: "2026-05-21",
      weekday: "Thu",
      base: "南昌固定酒店",
      theme: "抵达、放行李、低强度补给",
      load: "约4,000-6,000步，打车约8km",
      poiIds: ["nanchang-west-station", "nanchang-hanting-xuefu-east", "nanchang-vientiane"],
      schedule: [
        "13:00 抵达南昌西站。",
        "13:30-14:10 到汉庭学府大道东店，办理入住或寄存行李。",
        "16:30-19:30 步行到万象城/赣江南岸吃饭补给，早点休息。",
      ],
    },
    {
      day: 2,
      date: "2026-05-22",
      weekday: "Fri",
      base: "南昌固定酒店",
      theme: "省博 -> 滕王阁午餐 -> 老城轻量串联，晚上演唱会",
      load: "约10,000-13,000步；不回酒店走回头路；18:00后留给演唱会",
      poiIds: ["nanchang-hanting-xuefu-east", "jiangxi-museum", "tengwang-pavilion", "wanshou-palace", "bayi-memorial"],
      schedule: [
        "09:20 从酒店打车去江西省博物馆。",
        "09:50-12:00 江西省博物馆。",
        "12:00-14:20 直接去滕王阁/榕门路一带午餐和休息，不回酒店。",
        "14:20-16:00 滕王阁，控制游览时间。",
        "16:15-17:40 万寿宫/八一起义纪念馆周边短线，之后转演唱会。",
      ],
    },
    {
      day: 3,
      date: "2026-05-23",
      weekday: "Sat",
      base: "景德镇陶溪川/陶阳里",
      theme: "带箱离开南昌，晚上进入瓷都氛围",
      load: "约4,000-6,000步；跨城日不拖箱逛景点",
      poiIds: ["nanchang-hanting-xuefu-east", "nanchang-east-station", "jingdezhen-north-station", "jingdezhen-hanting-taoxichuan", "taoxichuan"],
      schedule: [
        "上午睡到自然醒，整理行李，不再安排远距离景点。",
        "12:30-13:20 打车到南昌东站。",
        "优先按12306样例D6360 15:18-16:12节奏买票；若想早到可看G3068 13:15-13:57，但带箱缓冲偏紧。",
        "抵达后先去陶溪川/陶阳里附近酒店放行李。",
        "傍晚陶溪川轻逛和晚餐。",
      ],
    },
    {
      day: 4,
      date: "2026-05-24",
      weekday: "Sun",
      base: "景德镇陶溪川/陶阳里",
      theme: "陶瓷文化主日：博物馆 -> 古窑 -> 御窑夜景",
      load: "约12,000-15,000步；景点间以短打车为主",
      poiIds: ["jingdezhen-hanting-taoxichuan", "ceramic-museum", "ancient-kiln", "imperial-kiln"],
      schedule: [
        "09:00 出发去景德镇中国陶瓷博物馆。",
        "09:20-11:50 中国陶瓷博物馆。",
        "午餐后去古窑民俗博览区。",
        "13:30-16:30 古窑民俗博览区。",
        "17:00-21:00 御窑博物馆/陶阳里晚段，晚餐后回酒店。",
      ],
    },
    {
      day: 5,
      date: "2026-05-25",
      weekday: "Mon",
      base: "三清山金沙索道口",
      theme: "景德镇高铁到上饶，再公共接驳进三清山脚",
      load: "约4,000-6,000步；无长途打车；下午只做休整",
      poiIds: ["jingdezhen-hanting-taoxichuan", "jingdezhen-north-station", "shangrao-station", "sanqingshan-hanting-jinsha"],
      schedule: [
        "07:50 退房，带行李短打车到景德镇北站。",
        "09:03-09:55 乘G1456节奏到上饶站，目标日需12306刷新。",
        "10:30-12:10 上饶站/汽车东站接旅游班车或公共接驳到三清山脚。",
        "12:30 后入住或寄存行李，午餐、补给、休息。",
        "晚上不再转场，为次日早上山保留体力。",
      ],
    },
    {
      day: 6,
      date: "2026-05-26",
      weekday: "Tue",
      base: "上饶站离开",
      theme: "三清山压缩版高光，下午公共接驳回上饶离开",
      load: "约14,000-18,000步；按Layer 3压缩经典线执行，雨雾切轻量核心线",
      poiIds: ["sanqingshan-hanting-jinsha", "sanqingshan-jinsha-lower", "sanqingshan-jinsha-upper", "sanqingshan-python", "sanqingshan-goddess", "sanqingshan-sunshine-coast", "sanqingshan-west-coast", "sanqingshan-jinsha-upper", "sanqingshan-jinsha-lower", "sanqingshan-hanting-jinsha", "shangrao-station"],
      schedule: [
        "06:45 酒店早餐，行李寄存在酒店或前台。",
        "07:15 到金沙索道下站，尽量第一批上山。",
        "07:45-09:20 金沙索道上站后先完成巨蟒出山、女神峰/东方女神。",
        "09:20-12:40 天气清楚走阳光海岸+西海岸压缩视野段；雨雾或排队严重则切轻量核心线。",
        "12:40-13:30 回到金沙索道上站附近，补给、排队下山；13:30后不再向远支线扩展。",
        "14:00-15:40 公共班车/接驳回上饶站。",
        "16:00 进站，17:00离开。",
      ],
    },
  ],
  dailySegments: [
    { day: 1, from: "nanchang-west-station", to: "nanchang-hanting-xuefu-east", luggage: true, transport: { drivingKm: 8.0, drivingMin: 17, note: "带箱到达，优先打车；也可地铁但换乘/步行不如打车稳。" } },
    { day: 1, from: "nanchang-hanting-xuefu-east", to: "nanchang-vientiane", transport: { walkingM: 480, walkingMin: 8, note: "500米以内，步行优先。" } },
    { day: 1, from: "nanchang-vientiane", to: "nanchang-hanting-xuefu-east", transport: { walkingM: 480, walkingMin: 8, note: "回酒店早休息。" } },
    { day: 2, from: "nanchang-hanting-xuefu-east", to: "jiangxi-museum", transport: { drivingKm: 8.5, drivingMin: 16, note: "跨区且上午赶开馆，打车更稳。" } },
    { day: 2, from: "jiangxi-museum", to: "tengwang-pavilion", transport: { drivingKm: 4.3, drivingMin: 12, note: "省博后直接去滕王阁附近午餐，避免回酒店走回头路。" } },
    { day: 2, from: "tengwang-pavilion", to: "wanshou-palace", transport: { walkingM: 1499, walkingMin: 28, note: "1.5km边界，体感好可步行，热/雨则打车。" } },
    { day: 2, from: "wanshou-palace", to: "bayi-memorial", transport: { walkingM: 369, walkingMin: 7, note: "500米以内，步行优先。" } },
    { day: 2, from: "bayi-memorial", to: "nanchang-hanting-xuefu-east", transport: { drivingKm: 6.9, drivingMin: 13, note: "如直接去演唱会场馆，此段替换为场馆路线；若不回酒店可删除此段。" } },
    { day: 3, from: "nanchang-hanting-xuefu-east", to: "nanchang-east-station", luggage: true, transport: { drivingKm: 23.4, drivingMin: 26, note: "带箱跨城，推荐打车直达南昌东站。" } },
    { day: 3, from: "nanchang-east-station", to: "jingdezhen-north-station", luggage: true, transport: { rail: "12306样例主推D6360，南昌东15:18 -> 景德镇北16:12，约54分钟，二等座86元/人。", railMin: 54, note: "下午离开南昌的核心交通段；2026-05-23临近开售后重新查票。" } },
    { day: 3, from: "jingdezhen-north-station", to: "jingdezhen-hanting-taoxichuan", luggage: true, transport: { drivingKm: 8.7, drivingMin: 17, note: "抵达后先去酒店放行李。" } },
    { day: 3, from: "jingdezhen-hanting-taoxichuan", to: "taoxichuan", transport: { walkingM: 500, walkingMin: 8, note: "酒店在陶溪川附近，步行/短打车均可。" } },
    { day: 4, from: "jingdezhen-hanting-taoxichuan", to: "ceramic-museum", transport: { drivingKm: 6.0, drivingMin: 13, note: "周日开馆，建议早点到避开团客。" } },
    { day: 4, from: "ceramic-museum", to: "ancient-kiln", transport: { drivingKm: 4.7, drivingMin: 13, note: "博物馆到活态工艺，主题递进。" } },
    { day: 4, from: "ancient-kiln", to: "imperial-kiln", transport: { drivingKm: 4.1, drivingMin: 12, note: "御窑晚段和夜景更合适。" } },
    { day: 4, from: "imperial-kiln", to: "jingdezhen-hanting-taoxichuan", transport: { drivingKm: 3.1, drivingMin: 9, note: "晚上回酒店短打车。" } },
    { day: 5, from: "jingdezhen-hanting-taoxichuan", to: "jingdezhen-north-station", luggage: true, transport: { drivingKm: 8.7, drivingMin: 17, note: "退房后短打车到景德镇北，不安排拖箱景点。" } },
    { day: 5, from: "jingdezhen-north-station", to: "shangrao-station", luggage: true, transport: { rail: "12306样例主推G1456，景德镇北09:03 -> 上饶09:55，约52分钟，二等座63.5元/人。", railMin: 52, note: "删除婺源/篁岭后的核心转场；目标日需临近开售后刷新。" } },
    { day: 5, from: "shangrao-station", to: "sanqingshan-hanting-jinsha", luggage: true, transport: { shuttle: "上饶站旁汽车东站/客运点到三清山旅游班车或公共接驳，公开攻略票价约27元/人，班次需赣悦行/当地客运刷新。", shuttleMin: 95, unitCny: 27, note: "用班车/公共接驳替代75km长途打车，符合非必要打车不超过1小时约束。" } },
    { day: 6, from: "sanqingshan-hanting-jinsha", to: "sanqingshan-jinsha-lower", transport: { drivingKm: 1.2, drivingMin: 4, walkingM: 1200, walkingMin: 18, note: "早上可短打车或步行到金沙索道，节省登山前体力。" } },
    { day: 6, from: "sanqingshan-jinsha-lower", to: "sanqingshan-jinsha-upper", transport: { cableway: "金沙索道上行，时间和票务以当日公告为准。", walkingMin: 12, note: "地图用直连表示索道，不代表步行导航。" } },
    { day: 6, from: "sanqingshan-jinsha-upper", to: "sanqingshan-python", transport: { walkingM: 700, walkingMin: 25, note: "上站后先拍巨蟒出山，形成第一段核心看点。" } },
    { day: 6, from: "sanqingshan-python", to: "sanqingshan-goddess", transport: { walkingM: 350, walkingMin: 12, note: "巨蟒出山与女神峰相邻，先完成必拍点。" } },
    { day: 6, from: "sanqingshan-goddess", to: "sanqingshan-sunshine-coast", transport: { walkingM: 1100, walkingMin: 45, note: "晴天保留阳光海岸；雨雾或排队严重时从这里折返。" } },
    { day: 6, from: "sanqingshan-sunshine-coast", to: "sanqingshan-west-coast", transport: { walkingM: 1800, walkingMin: 70, note: "远支线，只有体力、天气和时间都允许时进入。" } },
    { day: 6, from: "sanqingshan-west-coast", to: "sanqingshan-jinsha-upper", transport: { walkingM: 2200, walkingMin: 85, note: "13:30前必须回到金沙索道上站方向，否则直接放弃西海岸深段。" } },
    { day: 6, from: "sanqingshan-jinsha-upper", to: "sanqingshan-jinsha-lower", transport: { cableway: "金沙索道下行，必须刷新末班和排队时间。", walkingMin: 12, note: "下山后回酒店取行李。" } },
    { day: 6, from: "sanqingshan-jinsha-lower", to: "sanqingshan-hanting-jinsha", transport: { drivingKm: 1.2, drivingMin: 4, walkingM: 1200, walkingMin: 18, note: "下山后回酒店取行李。" } },
    { day: 6, from: "sanqingshan-hanting-jinsha", to: "shangrao-station", luggage: true, transport: { shuttle: "三清山脚到上饶站公共班车/接驳，按27元/人估算，实际班次需提前确认。", shuttleMin: 95, unitCny: 27, note: "避免超过1小时的非必要长途打车；如果班车时间不匹配，需要调整下山时间或恢复第7天。" } },
  ],
};

if (typeof module !== "undefined") {
  module.exports = { tripData };
}

if (typeof window !== "undefined") {
  window.TRIP_DATA = tripData;
}
